
Server:
 Port: 8080

Db:
  Password: root
  Url: 127.0.0.1
  UserName: root
  Name: userdb
  Dialect: mysql
  Port: 3306
  Driver: mysql
  LogLevel: 4

# 	db, err := sql.Open("mysql", "root:test@tcp(127.0.0.1:3306)/testdb")
